config/routes.rb
Rails.application.routes.draw do
  #get 'tickets/index'
  root "movies#index"
  # match ':controller(/:action(/:id))', :via => :get



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'sign_out' => 'user_sessions#destroy'
  get 'users/check_out'
  get 'users/register'
  get 'users/resetArrayChairsId'
  get 'users/pay'
  get 'users/manage_movies' => 'users#manage_movies'

  post 'users/pay'
  post 'users/addSelectedChair'
  post 'users/removeSelectedChair'

  get 'dashboard' => 'users#dashboard'
  get 'login' => 'user_sessions#login'
  get 'ticket/print' => 'tickets#print'
  get 'tickets/rank'

  resources :sessions
  resources :rooms
  resources :theaters
  resources :movies
  resources :user_sessions
  resources :movie_sessions
  resources :tickets, only: [:index]


  resources :users do
  	post :buy_ticket, on: :member
    get :check_out, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_theater
	has_many :sessions
	has_attached_file :image, styles: { medium: "300x300>", thumb: "75x100#" }, default_url: "/assets/missing75x100.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/movie_theater.rb
class MovieTheater < ApplicationRecord
	belongs_to :movie
	belongs_to :theater
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	has_many :tickets
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_one :ticket
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :theater
  belongs_to :template

  def print_theater
    " Theater: #{theater.name} / Room: #{id} / Capacity: #{template.row * template.col}"
  end

  def tickets
    "#{template.row * template.col}"
  end

end

app/models/session.rb
class Session < ApplicationRecord

	belongs_to :room
	belongs_to :movie
	has_many :tickets

	def reservatedchairs
		chairs = []
		puts "--------------------------------------"
		tickets.each do |t|
			puts "--------------------------------------"
			puts t.chair
			puts "--------------------------------------"
			chairs.push(t.chair)
		end
		chairs
	end

end

app/models/template.rb
class Template < ApplicationRecord
	has_many :rooms

	def print_template
		"Columns: #{col} / Rows: #{row} / Total: #{row*col}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	has_many :movie_theater
	has_many :rooms
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :purchase
	belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
	has_many :purchases
	has_many :tickets, :through => :purchases
	has_secure_password

	validates :email, :uniqueness => true

	def is_admin
		self.role.downcase == "admin"
	end
end

app/controllers/movie_sessions_controller.rb
class MovieSessionsController < ApplicationController
	def index
		@sessions = Session.all.paginate(page: params[:page], per_page: 6)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :needs_clearance, :only => [:index, :edit, :new]

  def index
    @rooms = Room.all.order(:theater_id)
  end

  def new
    @room =Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.capacity = @room.template.col*@room.template.row
    
    if @room.save
      flash[:success] = "Room created"
      redirect_to root_path
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success]="Room edited"
      redirect_to rooms_path
    end
end

  def edit
    @room = Room.find (params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:theater_id,:template_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_movies_helper.rb
module CrudMoviesHelper
end

app/helpers/movie_sessions_helper.rb
module MovieSessionsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movie_sessions/index.html.erb
<!--TODO: add pagination-->
<div class="container">
	
	<div class="row">
		<% @sessions.each do |s| %>
		<div class="col-lg-4 col-md-4  col-xs-12 col-lg-offset-1 col-md-offset-1" >
		
		
			<table border="1" class="table">
				<tr>
					<th colspan="2"><%= s.movie.title %></th>
				</tr>
				<tr>
					<td colspan="2">
						Date: 
						<%= s.date.strftime("%b, %d - %Y") %>
					</td>
					
				</tr>
				<tr>
					<td>
						Price:
						<%= number_to_currency(current_user.student ? s.price/2 : s.price) %>
					</td>

				</tr>
				<tr>
					<td>
						<%= s.movie.storyline %>
					</td>

				</tr>
				<tr>
					<td>
						<%= image_tag s.movie.image.url(:thumb) %>
					</td>

				</tr>
				<tr>
					 <td colspan="2">
					 	<% if not (s.movie.censorship > current_user.age) %>
					 		<% if s.tickets.count < s.room.capacity %>
					 			<%= link_to "Buy a ticket!", users_check_out_path(session_id: s.id) %>
					 		<%else%>
					 			No Tickets available :(
					 		<%end%>
						<% else %>
							You have to be this old (<%= s.movie.censorship %>) to ride this ride
						<% end %><br>
						(<%= s.room.capacity-s.tickets.count %> Available)
					</td>

				</tr>
				<!--End of table-->
			</table>
		</div>
		<% end %>
		<!--<div class="clearfix" ></div> -->

	</div>
	<div class="row">
		<div class="col-lg-4 col-md-4  col-xs-12 col-lg-offset-4 col-md-offset-4">
			<%= will_paginate @sessions, inner_window: 2 %>
		</div>
	</div>
	
	
<!-- End of container-->
<br/>

<div class="row">
		<div class="col-lg-4 col-md-4  col-xs-12 col-lg-offset-4 col-md-offset-4">
			<%= link_to("Tickets", 
				{:controller => 'tickets',
					:action => 'index'},
					class: "btn btn-primary") %>
			<% if current_user.role.eql?"admin" %>
				<%= link_to("Rank", 
					{:controller => 'tickets',
						:action => 'rank'},
						class: "btn btn-primary") %>
			<% end %>
			<%= link_to("Movies", 
				{:controller => 'movies',
					:action => 'index'},
					class: "btn btn-primary") %>
			
		</div>
		
	</div>
</div>