config/routes.rb
Rails.application.routes.draw do
  #get 'tickets/index'
  root "movies#index"
  # match ':controller(/:action(/:id))', :via => :get



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'sign_out' => 'user_sessions#destroy'
  get 'users/check_out'
  get 'users/register'
  get 'users/resetArrayChairsId'
  get 'users/pay'
  get 'users/manage_movies' => 'users#manage_movies'

  post 'users/pay'
  post 'users/addSelectedChair'
  post 'users/removeSelectedChair'

  get 'dashboard' => 'users#dashboard'
  get 'login' => 'user_sessions#login'
  get 'ticket/print' => 'tickets#print'
  get 'tickets/rank'

  resources :sessions
  resources :rooms
  resources :theaters
  resources :movies
  resources :user_sessions
  resources :movie_sessions
  resources :tickets, only: [:index]


  resources :users do
  	post :buy_ticket, on: :member
    get :check_out, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_theater
	has_many :sessions
	has_attached_file :image, styles: { medium: "300x300>", thumb: "75x100#" }, default_url: "/assets/missing75x100.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/movie_theater.rb
class MovieTheater < ApplicationRecord
	belongs_to :movie
	belongs_to :theater
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	has_many :tickets
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_one :ticket
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :theater
  belongs_to :template

  def print_theater
    " Theater: #{theater.name} / Room: #{id} / Capacity: #{template.row * template.col}"
  end

  def tickets
    "#{template.row * template.col}"
  end

end

app/models/session.rb
class Session < ApplicationRecord

	belongs_to :room
	belongs_to :movie
	has_many :tickets

	def reservatedchairs
		chairs = []
		puts "--------------------------------------"
		tickets.each do |t|
			puts "--------------------------------------"
			puts t.chair
			puts "--------------------------------------"
			chairs.push(t.chair)
		end
		chairs
	end

end

app/models/template.rb
class Template < ApplicationRecord
	has_many :rooms

	def print_template
		"Columns: #{col} / Rows: #{row} / Total: #{row*col}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	has_many :movie_theater
	has_many :rooms
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :purchase
	belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
	has_many :purchases
	has_many :tickets, :through => :purchases
	has_secure_password

	validates :email, :uniqueness => true

	def is_admin
		self.role.downcase == "admin"
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :needs_clearance, :only => [:edit, :new]
  before_action :needs_login, :only => [:show]

  def show
      @movie = Movie.find(params[:id])
  end

  def index
      @movies = Movie.all
  end

  def new
      @movie = Movie.new
  end

  def create
    @movie =Movie.new(movie_params)
    if @movie.save
      flash[:success]="Movie created"
      redirect_to root_path
    end
  end

  def update
    @movie =Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      flash[:success]="Movie edited"
      redirect_to movies_path
    end
end
  def edit
    @movie = Movie.find (params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.sessions.count == 0
      @movie.destroy
    else
      flash[:error]="This movie has available session. It cannot be deleted"
    end
    redirect_to movies_path

  end

  def movie_params
    params.require(:movie).permit(:title, :censorship, :storyline, :image, :category)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :needs_clearance, :only => [:index, :edit, :new]

  def index
    @rooms = Room.all.order(:theater_id)
  end

  def new
    @room =Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.capacity = @room.template.col*@room.template.row
    
    if @room.save
      flash[:success] = "Room created"
      redirect_to root_path
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success]="Room edited"
      redirect_to rooms_path
    end
end

  def edit
    @room = Room.find (params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:theater_id,:template_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :needs_clearance, :only => [:dashboard, :manage_movies]
	before_action :needs_login, :only => [:check_out]

	@@arrayChairsNameSit = []
	
	def resetArrayChairsId
		@@arrayChairsNameSit = []
		#printObject(@@arrayChairsNameSit)
	end

	def addSelectedChair
		@@arrayChairsNameSit << params[:sit]
		#printObject(@@arrayChairsNameSit)
	end

	def removeSelectedChair
		@@arrayChairsNameSit.delete(params[:sit])
		#printObject(@@arrayChairsNameSit)
	end

	def dashboard
		@movies = Movie.all
		@sessions = Room.all
		@theaters = Theater.all
		@rooms = Room.all
	end

	def manage_movies
		@movies = Movie.all
	end

	def register
		@user = User.new
	end

	def index
		@users = User.all
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "User added"
			redirect_to root_path
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	    if @user.update_attributes(user_params)
	    	flash[:success] = "User edited"
	    	redirect_to users_path
	    end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User deleted"
		redirect_to users_path
	end

	def buy_ticket
		session = Session.find(params[:session])
		v = params[:quantity]
		ticket = Ticket.new(
			status: false, 
			price: current_user.student ? session.price/2 : session.price, 
			session_id: session.id )
		current_user.tickets << ticket
		redirect_to tickets_path
	end

	def check_out
		@session = Session.find(params[:session_id])
		@price = current_user.student ? @session.price/2 : @session.price
		@ntAvailable = 4-current_user.tickets.where(session_id: params[:session_id]).count

		#Number of cols and rows from the template of the room
		@col = @session.room.template.col
		@row = @session.room.template.row

		#Array of chairs that are reservated
		@chairs = @session.reservatedchairs

		if @ntAvailable < 1
			redirect_to movie_sessions_path, info: "You have already bought the Maximum available tickets."
		end 
	end

	def pay
		@numbTic = current_user.tickets.where(session_id: params[:session_id])
		qt = params[:quantity].to_i
		totalTicSession = @numbTic.size + qt

		msg = "You already bought " +  @numbTic.size.to_s  + " tickets from this session. Maximum is 4."

		if totalTicSession > 4

			redirect_to users_check_out_path(session_id: params[:session_id]), info: msg
		else
			session = Session.find(params[:session_id])
			price = current_user.student ? session.price/2 : session.price

			p = Purchase.new(total: (qt*price),
					user_id: current_user.id,
					installment_times: Integer(params[:installments]),
					payment: params[:method]
				)
			p.save!
			qt.times do |t|
				if @@arrayChairsNameSit.empty?
					p.tickets.create!(status:true, price: price, session_id: session.id)
				else
					sit = @@arrayChairsNameSit.delete_at(0)
					p.tickets.create!(status:true, price: price, session_id: session.id, chair: sit)
				end	
			end

			redirect_to root_path, success: "The ticket was successfully bought"
		end
		
	end

	def user_params
    	params.require(:user).permit(:name, :email, :age, :student, :password)
  	end

  	

  	private

  		def printObject(object)
  			puts ""
  			puts "****** CURRENT OBJECT ******" 
			puts object
			puts "****** END OBJECT ******"
			puts ""
		end 

		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_movies_helper.rb
module CrudMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/_movie_ad.html.erb
<div class="col-lg-3 col-md-3 col-sm-3 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
	<%= link_to movie_path(m) do %>
			<h4 align="center"><%= m.title %> </h4>
	<% end %>
	<div class="media">
		<div class="media-left media-middle">
			<%= image_tag m.image.url(:thumb) %> 
		</div>
		<div class="media-body">
			<%= m.storyline %>
		</div>
	</div>


	<small>Sessions: <%= m.sessions.count %></small>

	<% if current_user != nil %>
		<% if  current_user.role.eql?"admin"%>
			<br> <%=link_to "Edit",
			edit_movie_path(m),
			class: "btn btn-info btn-sm" %>
			<%=link_to "Delete",
			movie_path(m),
			method: :delete,
			class: "btn btn-info btn-sm"%>
		<% end %>
	<% end %> 
</div>

app/views/movies/_movie_form.html.erb
<%= form_for @movie, html: {multipart: true } do |m| %>
        <%= m.label :title %>
        <%= m.text_field :title, required: true, class: "form-control" %><br>

        <%= m.label :censorship%>
        <%= m.select :censorship, [10,12,14,16,18], required:true%><br><br>

        <%= m.label :category%>
        <%= m.text_field :category, required:true%><br><br>

        <%= m.label :storyline %>
        <%= m.text_field :storyline, class: "form-control" %><br>

        <%= m.label :image %>
        <%= m.file_field :image, required: true%><br>

        <%= m.submit "Edit", class: "form-control btn-primary btn-lg" %>
        <%= link_to "Cancel", users_manage_movies_path, class: "btn btn-danger" %>
    <% end %>

app/views/movies/edit.html.erb
<div class="col-md-4 col-md-offset-4">

    <%= render(:partial => "movie_form", :locals => { :m => @movie}) %>

</div>

app/views/movies/index.html.erb
	<h1 align="center">Movies</h1>
<div class="container" style="padding:10px 10px ;">
	<div class = "row">
	<% @movies.each do |m| %>
		<%= render(:partial => "movie_ad", :locals => { :m => m}) %>
	<% end %>
	</div>
	<div class= "row">
	</br>
	</br>
		<div class="col-lg-3 col-md-3 col-sm-3 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
		<% if current_user != nil %>
		<%=link_to "Create", new_movie_url,class: "btn btn-info btn-sm" %><br>
		<%end %>
		</div>
	</div>
	

</div>

app/views/movies/new.html.erb
<div class="col-md-4 col-md-offset-4">

    <%= form_for(@movie) do |m| %>
        <%= m.label :title %>
        <%= m.text_field :title, required: true,placeholder: "Enter your email",class: "form-control" %><br>

        <%= m.label :censorship%>
        <%= m.select :censorship, [10,12,14,16,18], required:true%><br><br>

        <%= m.label :storyline %>
        <%= m.text_field :storyline, required: true, class: "form-control" %><br>

        <%= m.submit "Register", class: "form-control btn-primary" %>
    <% end %>
    <br>
    <%= link_to "Cancel", users_manage_movies_path, class: "btn btn-danger" %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
All sessions of this movie
<!--TODO: add pagination-->
<div class="container">

	<div class="row">
		<% @movie.sessions.each do |s| %>
		<div class="col-lg-4 col-md-6  col-xs-12" >


			<table border="1" class="table">
				<tr>
					<th colspan="2"><%= s.movie.title %></th>
				</tr>
				<tr>
					<td colspan="2">
						Date:
						<%= s.date.strftime("%b, %d - %Y") %>
					</td>

				</tr>
				<tr>
					<td>
						Price:
						<%= number_to_currency(current_user.student ? s.price/2 : s.price) %>
					</td>

				</tr>
				<tr>
					<td>
						<%= s.movie.storyline %>
					</td>

				</tr>
				<tr>
					 <td colspan="2">
					 	<% if not (s.movie.censorship > current_user.age) %>
					 		<% if s.tickets.count < s.room.capacity %>
					 			<%= link_to "Buy a ticket!", users_check_out_path(session_id: s.id) %>
					 		<%else%>
					 			No Tickets available :(
					 		<%end%>
						<% else %>
							You have to be this old (<%= s.movie.censorship %>) to ride this ride
						<% end %><br>
						(<%= s.room.capacity-s.tickets.count %> Available)
					</td>

				</tr>
				<!--End of table-->
			</table>
		</div>
		<% end %>
		<div class="clearfix" ></div>

	</div>

<!-- End of container-->
<br/>
<%= link_to("Tickets",
		{:controller => 'tickets',
			:action => 'index'},
			class: "btn btn-primary") %>
	<%= link_to("Movies",
		{:controller => 'movies',
			:action => 'index'},
			class: "btn btn-primary") %>
<br/>
<br/>
</div>