config/routes.rb
Rails.application.routes.draw do
  #get 'tickets/index'
  root "movies#index"
  # match ':controller(/:action(/:id))', :via => :get



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'sign_out' => 'user_sessions#destroy'
  get 'users/check_out'
  get 'users/register'
  get 'users/resetArrayChairsId'
  get 'users/pay'
  get 'users/manage_movies' => 'users#manage_movies'

  post 'users/pay'
  post 'users/addSelectedChair'
  post 'users/removeSelectedChair'

  get 'dashboard' => 'users#dashboard'
  get 'login' => 'user_sessions#login'
  get 'ticket/print' => 'tickets#print'
  get 'tickets/rank'

  resources :sessions
  resources :rooms
  resources :theaters
  resources :movies
  resources :user_sessions
  resources :movie_sessions
  resources :tickets, only: [:index]


  resources :users do
  	post :buy_ticket, on: :member
    get :check_out, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_theater
	has_many :sessions
	has_attached_file :image, styles: { medium: "300x300>", thumb: "75x100#" }, default_url: "/assets/missing75x100.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/movie_theater.rb
class MovieTheater < ApplicationRecord
	belongs_to :movie
	belongs_to :theater
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	has_many :tickets
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_one :ticket
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :theater
  belongs_to :template

  def print_theater
    " Theater: #{theater.name} / Room: #{id} / Capacity: #{template.row * template.col}"
  end

  def tickets
    "#{template.row * template.col}"
  end

end

app/models/session.rb
class Session < ApplicationRecord

	belongs_to :room
	belongs_to :movie
	has_many :tickets

	def reservatedchairs
		chairs = []
		puts "--------------------------------------"
		tickets.each do |t|
			puts "--------------------------------------"
			puts t.chair
			puts "--------------------------------------"
			chairs.push(t.chair)
		end
		chairs
	end

end

app/models/template.rb
class Template < ApplicationRecord
	has_many :rooms

	def print_template
		"Columns: #{col} / Rows: #{row} / Total: #{row*col}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	has_many :movie_theater
	has_many :rooms
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :purchase
	belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
	has_many :purchases
	has_many :tickets, :through => :purchases
	has_secure_password

	validates :email, :uniqueness => true

	def is_admin
		self.role.downcase == "admin"
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :needs_clearance, :only => [:edit, :new]
  before_action :needs_login, :only => [:show]

  def show
      @movie = Movie.find(params[:id])
  end

  def index
      @movies = Movie.all
  end

  def new
      @movie = Movie.new
  end

  def create
    @movie =Movie.new(movie_params)
    if @movie.save
      flash[:success]="Movie created"
      redirect_to root_path
    end
  end

  def update
    @movie =Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      flash[:success]="Movie edited"
      redirect_to movies_path
    end
end
  def edit
    @movie = Movie.find (params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.sessions.count == 0
      @movie.destroy
    else
      flash[:error]="This movie has available session. It cannot be deleted"
    end
    redirect_to movies_path

  end

  def movie_params
    params.require(:movie).permit(:title, :censorship, :storyline, :image, :category)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :needs_clearance, :only => [:index, :edit, :new]

  def index
    @rooms = Room.all.order(:theater_id)
  end

  def new
    @room =Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.capacity = @room.template.col*@room.template.row
    
    if @room.save
      flash[:success] = "Room created"
      redirect_to root_path
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success]="Room edited"
      redirect_to rooms_path
    end
end

  def edit
    @room = Room.find (params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:theater_id,:template_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :needs_clearance, :only => [:dashboard, :manage_movies]
	before_action :needs_login, :only => [:check_out]

	@@arrayChairsNameSit = []
	
	def resetArrayChairsId
		@@arrayChairsNameSit = []
		#printObject(@@arrayChairsNameSit)
	end

	def addSelectedChair
		@@arrayChairsNameSit << params[:sit]
		#printObject(@@arrayChairsNameSit)
	end

	def removeSelectedChair
		@@arrayChairsNameSit.delete(params[:sit])
		#printObject(@@arrayChairsNameSit)
	end

	def dashboard
		@movies = Movie.all
		@sessions = Room.all
		@theaters = Theater.all
		@rooms = Room.all
	end

	def manage_movies
		@movies = Movie.all
	end

	def register
		@user = User.new
	end

	def index
		@users = User.all
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "User added"
			redirect_to root_path
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	    if @user.update_attributes(user_params)
	    	flash[:success] = "User edited"
	    	redirect_to users_path
	    end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User deleted"
		redirect_to users_path
	end

	def buy_ticket
		session = Session.find(params[:session])
		v = params[:quantity]
		ticket = Ticket.new(
			status: false, 
			price: current_user.student ? session.price/2 : session.price, 
			session_id: session.id )
		current_user.tickets << ticket
		redirect_to tickets_path
	end

	def check_out
		@session = Session.find(params[:session_id])
		@price = current_user.student ? @session.price/2 : @session.price
		@ntAvailable = 4-current_user.tickets.where(session_id: params[:session_id]).count

		#Number of cols and rows from the template of the room
		@col = @session.room.template.col
		@row = @session.room.template.row

		#Array of chairs that are reservated
		@chairs = @session.reservatedchairs

		if @ntAvailable < 1
			redirect_to movie_sessions_path, info: "You have already bought the Maximum available tickets."
		end 
	end

	def pay
		@numbTic = current_user.tickets.where(session_id: params[:session_id])
		qt = params[:quantity].to_i
		totalTicSession = @numbTic.size + qt

		msg = "You already bought " +  @numbTic.size.to_s  + " tickets from this session. Maximum is 4."

		if totalTicSession > 4

			redirect_to users_check_out_path(session_id: params[:session_id]), info: msg
		else
			session = Session.find(params[:session_id])
			price = current_user.student ? session.price/2 : session.price

			p = Purchase.new(total: (qt*price),
					user_id: current_user.id,
					installment_times: Integer(params[:installments]),
					payment: params[:method]
				)
			p.save!
			qt.times do |t|
				if @@arrayChairsNameSit.empty?
					p.tickets.create!(status:true, price: price, session_id: session.id)
				else
					sit = @@arrayChairsNameSit.delete_at(0)
					p.tickets.create!(status:true, price: price, session_id: session.id, chair: sit)
				end	
			end

			redirect_to root_path, success: "The ticket was successfully bought"
		end
		
	end

	def user_params
    	params.require(:user).permit(:name, :email, :age, :student, :password)
  	end

  	

  	private

  		def printObject(object)
  			puts ""
  			puts "****** CURRENT OBJECT ******" 
			puts object
			puts "****** END OBJECT ******"
			puts ""
		end 

		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_movies_helper.rb
module CrudMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h1 align="center">Edit Room</h1>
    <%= form_for(@room) do |r| %>
        <%= r.label :theater_id %>
        <%= r.collection_select :theater_id, Theater.all,:id,:name,include_blank: false, class: "form-control"%><br><br>

        <%= r.label :size%>
        <%= r.collection_select :template_id, ::Template.all,:id,:print_template,class: "form-control"%>

        <%= r.submit "Edit", class: "form-control btn-primary btn-lg" %>
    <% end %>
    <br>
    <%= link_to "Cancel", rooms_path, class: "btn btn-danger" %>
</div>

app/views/rooms/index.html.erb
<div class="col-md-6 col-md-offset-3">
    <h1 align="center">Rooms List</h1>
    <%=link_to "Create", new_room_url,class: "btn btn-success btn-sm" %>
    <%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-info btn-sm" %><br><br>
    <table class="table table-striped">
      <tr>
      <td align="center">Theater</td>
      <td align="center">Room</td>
      <td></td>
      <td></td>
      </tr>
    <%@rooms.each do |room| %>
        <tr>
        <td><%= room.theater.name %></td>
        <td>Columns:<%= room.template.col%> Rows:<%=room.template.row %> Total:<%=room.template.row * room.template.col%></td>
         <td><%=link_to "Edit", edit_room_path(room),class: "btn btn-info btn-sm" %></td>
         <td> <%=link_to "Destroy",room_path(room),method: :delete,class: "btn btn-danger btn-sm"%> </td>
        </tr>
    <% end %>
    </table>
</div>

<style type="text/css">
  td
  {
    padding: 10px;
  }
</style>

app/views/rooms/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h1 align="center">Edit Room</h1>
    <%= form_for(@room) do |r| %>
        <%= r.collection_select :theater_id, Theater.all,:id,:name,include_blank: false, class: "form-control"%><br><br>

        <%= r.label :size%>
        <%= r.collection_select :template_id, ::Template.all,:id,:print_template,class: "form-control"%>

        <%= r.submit "Register", class: "form-control btn-primary" %>
    <% end %>
    <br>
    <%= link_to "Cancel", rooms_path, class: "btn btn-danger" %>
</div>

app/views/users/check_out.html.erb
<div class="row">
	<div class="check-out-container col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-4">
		<%= render 'flash_messages' %>
		<h2>Check out</h2>
		<h3><%= @session.movie.title %></h3>
		<h5><%= @session.date.strftime("%b, %d - %Y") %></h5><br><br>

		<%= form_tag users_pay_path do%>
		<!-- Select chair-->
		<div class="chair-distribution">
			<table>
				<% count = 0 %>
				<% @row.times do |r| %>
					<tr>
						<% @col.times do |c| %>
							<th>
							<% chairId = "#{r}-#{c}"  %>
							<% if "#{@session.reservatedchairs}".include?(chairId) %> 
								<div id="chair-<%= "#{r}-#{c}" %>" class="reserved-chair">
									<img src='/assets/reservedchair-32.png' alt='ReservedChair'/>
								</div>	
							<% else %>
								<div id="chair-><%= "#{r}-#{c}" %>" class="chair">
									<img src='/assets/emptychair-32.png' alt='EmptyChair'/>
								</div>
							<% end %>

								
							</th>
							<% count = count+1 %>
						<% end %>
					</tr>
				<% end %>
			</table>
			

		</div>

		<!-- End Select chair -->
			<b>How many tickets do you want?</b>

			<%= select_tag :quantity, options_for_select(1..[@session.room.capacity-@session.tickets.count, @ntAvailable].min), class: "quantity", data: { quantity: 1 } %>

			<br><br>

			<b>Choose your payment method</b>
			<%= select_tag :method, options_for_select(["Credit", "Debit"]), class: "payment_option" %>
			<% puts :method %>
			<br><br>

			<div id="installments" style="display:<%= @price >= 30 ? "inline" : "none" %>">
			<b>You have installments options</b>
			<%= select_tag :installments, options_for_select(1..2), class: "installments", data: { quantity: 1 } %>
			<br><br>
			</div>


			<h4>Credit Card</h4>
			<b>Number</b>
			<input pattern="[0-9]{16,16}" min="1000000000000000" max="9999999999999999" id="sessionNo" name="sessionNum" maxlength="16" required="required"/><br><br>
			<b>Expiration date: </b>
			<%= select_tag :month, options_for_select(1..12) %>/
			<%= select_tag :year, options_for_select(2017..2025) %><br><br>
			<b>Security Code:</b>
			<input type="text" maxlength="3" id="sessionNo" name="sessionNum" required="required"/><br><br>
			<br><br>

			<h4>Your total:
		 	$<span id="total"><%= current_user.student ? @session.price/2 : @session.price %></span>
			</h4>

			<br>
			
			<%= hidden_field_tag :session_id, @session.id %>
			<%= submit_tag "Pay", class: "form-control btn btn-primary", 'data-disable-with' => "Please wait.." %>
		<% end %>
		
	<br/>	


	</div>
</div>
<br/>
<div class="row">
	<div class="cancel-purchase col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-4">
		<%= link_to("Cancel", 
			{:controller => 'movie_sessions',
				:action => 'index'},
				class: "btn btn-primary") %>
	</div>
</div>

<script type="text/javascript">
//$(":input").inputmask();

var quantity = document.getElementsByClassName("quantity")[0].value;
var numberChairsSelected = 0;
var divsSelectedChair = [];
var addIdChair;

$(function() {
  $(document).on('change', '.quantity', function() {
    // this == the element that fired the change event

    var value = parseFloat("<%= @price %>");
    quantity = document.getElementsByClassName("quantity")[0].value;

    installmentsOptions(quantity);
    resetArrayChairsId();
    resetSelectedChairs();

    document.getElementById("total").innerHTML = (value*quantity).toFixed(2).toString();
  });
});

$(function() {
  $(document).on('change', '.payment_option', function() {
    // this == the element that fired the change event
    var value = parseFloat("<%= @price %>");
    quantity = document.getElementsByClassName("quantity")[0].value;
    installmentsOptions(quantity);

    document.getElementById("total").innerHTML = (value*quantity).toFixed(2).toString();
  });
});

function installmentsOptions(qt)
{
	var value = parseFloat("<%= @price %>");
    var payment_option = document.getElementsByClassName("payment_option")[0].value;
    if(payment_option.localeCompare("Credit") == 0)
	    if (value*qt >= 30)
	    	document.getElementById("installments").style.display = 'inline';
	    else
	    	document.getElementById("installments").style.display = 'none';
	else
		document.getElementById("installments").style.display = 'none';
}
window.onload = installmentsOptions;

//Reset all selected chairs
function resetSelectedChairs()
{

	divsSelectedChair.forEach(function(div){
		document.getElementById(div.id).innerHTML = "<img src='/assets/emptychair-32.png' alt='EmptyChair'/>";
	});
	divsSelectedChair = [];
	numberChairsSelected = 0;
}

//Select chairs
$(function(){
	$(document).on('click', '.chair', function(){
		selectChair(this)
	});
});

//Eraese data when cancel a purchase
$(function(){
	$(document).on('click', '.cancel-purchase', function(){
		resetArrayChairsId();
		resetSelectedChairs();
	});
});

//javascript to select chairs
function selectChair(chairDiv)
{

	var statusChair = $(chairDiv).children("img").attr("alt");
	if(statusChair.localeCompare("EmptyChair") == 0 && numberChairsSelected < quantity){
		document.getElementById(chairDiv.id).innerHTML = "<img src='/assets/selectedchair-32.png' alt='SelectedChair'/>";
		numberChairsSelected++;
		divsSelectedChair.push(chairDiv);
		addChairIdIntoController(chairDiv.id);
	}else if((statusChair.localeCompare("SelectedChair"))== 0 ){
		numberChairsSelected--;
		document.getElementById(chairDiv.id).innerHTML = "<img src='/assets/emptychair-32.png' alt='EmptyChair'/>";
		removeChairIdFromController(chairDiv.id);
	}else{
		//TODO - print message for the limit of selected chairs
	}

}

//Rest Array of Chairs's Id in controller.
function resetArrayChairsId()
{
	$.ajax({
    	url: "resetArrayChairsId",
    	type: "get"
    });
}

//Add the id chair into Controller
function addChairIdIntoController(divIdChair)
{
	console.log(divIdChair);
	var strSit = divIdChair.substring(7);
	$.ajax({
    	url: "addSelectedChair",
    	type: "post",
    	data: {sit: strSit }
    });
}

//Remover the id chair from controller
function removeChairIdFromController(divIdChair)
{
	console.log(divIdChair);
	var strSit = divIdChair.substring(7);
	$.ajax({
    	url: "removeSelectedChair",
    	type: "post",
    	data: {sit: strSit }
    });
}




</script>

app/views/users/dashboard.html.erb
<h1 align="center">Dashboard</h1>


<div class="col-md-8 col-md-offset-2">

	<%= link_to "Back to main", root_path, class: "btn btn-success" %>

	<div class="category">
		<h3>Users</h3>
		To edit, create and delete users click <%= link_to "here", users_path %>
	</div>	

	<!-- MOVIES -->
	<div class="category">
		<h3>Movies</h3>
		To edit, create and delete movies click <%= link_to "here", users_manage_movies_path %>
	</div>


	<!-- THEATERS -->
	<div class="category">
		<h3>Theaters</h3>
		To edit, create and delete theaters click <%= link_to "here", theaters_path %>
	</div>


	<!-- Rooms -->
	<div class="category">
		<h3>Rooms</h3>
		To edit, create and delete theater's rooms click <%= link_to "here", rooms_path %>
	</div>

	<div class="category">
		<h3>Sessions</h3>
		To edit, create and delete movie's sessions click <%= link_to "here", sessions_path %>
	</div>

	<div class="category">
		<h3>Rank</h3>
		To view the rank of 10 most watched movies click <%= link_to "here", {:controller => 'tickets',
						:action => 'rank'} %>
	</div>


</div>

app/views/users/edit.html.erb
<div class="col-md-4 col-md-offset-4">
	<%= form_for(@user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name, required: true, class: "form-control" %><br>

		<%= f.label :email %>
		<%= f.email_field :email, required: true, class: "form-control" %><br>

		<%= f.label :age %>
		<%= f.number_field :age, required: true, class: "form-control" %><br>

		<%= f.label :student %>
		<%= f.select(:student, options_for_select([['Student', true], ['Not Student', false]]), {}, {class: "form-control"}) %><br>

		<%= f.label :role %>
		<%= f.select(:role, options_for_select(['customer', 'admin']), {}, {class: "form-control"}) %><br>

		<%= f.label :password %>
		<%= f.password_field :password, required: true, class: "form-control" %><br>

		<%= f.submit "Register", class: "form-control btn-primary" %>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="col-md-6 col-md-offset-3">
		<h3 align="center">Users (<%= @users.count %>)</h3>
		<%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-info btn-sm" %>
		<br>
		

	<table class="table table-striped">
	<tr>
		<td align="center">Name</td>
		<td align="center">Email</td>
		<td align="center">Age</td>
		<td align="center">Student</td>
		<td align="center">Role</td>
		<td></td>
		<td></td>
	</tr>

	<% @users.each do |u| %>
		<tr>
			
			<td><%= u.name %></td>
			<td align="center"><%= u.email %></td>
			<td align="center"><%= u.age %></td>
			<td align="center"><%= u.student %></td>
			<td align="center"><%= u.role %></td>

			<td><%=link_to_if u != current_user, "Edit", edit_user_path(u),class: "btn btn-info btn-sm" %></td> 
			<td><%=link_to_if u != current_user, "Delete",user_path(u),method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger btn-sm"%></td>
		</tr>
	<% end %>
</div>

app/views/users/manage_movies.html.erb
<div class="col-md-6 col-md-offset-3">
		<h3 align="center">Movies (<%= @movies.count %>)</h3>
		<%= link_to 'New Movie', new_movie_path, class: "btn btn-success btn-sm" %>
		<%= link_to "Back to Dashboard", dashboard_path, class: "btn btn-info btn-sm" %>
		<br>
		

	<table class="table table-striped">
	<tr>
		<td align="center">Title</td>
		<td align="center">Censorship</td>
		<td align="center">Sessions</td>
		<td></td>
		<td></td>
	</tr>

	<% @movies.each do |m| %>
		<tr>
			<td><%= m.title %></td>
			<td align="center"><%= m.censorship %></td>
			<td align="center"><%= m.sessions.count %></td>

			<td><%=link_to "Edit", edit_movie_path(m),class: "btn btn-info btn-sm" %></td> 
			<td><%=link_to "Delete",movie_path(m),method: :delete, data: {confirm: "Are you sure?"},class: "btn btn-danger btn-sm"%></td>
		</tr>
	<% end %>
</div>

app/views/users/register.html.erb
<div class="col-md-4 col-md-offset-4">
	
	<%= form_for(@user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name, required: true, class: "form-control" %><br>

		<%= f.label :email %>
		<%= f.email_field :email, required: true, class: "form-control" %><br>

		<%= f.label :age %>
		<%= f.number_field :age, required: true, class: "form-control" %><br>

		<%= f.label :student %>
		<%= f.select(:student, options_for_select([['Student', true], ['Not Student', false]]), {}, {class: "form-control"}) %><br>

		<%= f.label :password %>
		<%= f.password_field :password, required: true, class: "form-control" %><br>

		<%= f.submit "Register", class: "form-control btn-primary" %>
	<% end %>
</div>