config/routes.rb
Rails.application.routes.draw do
  #get 'tickets/index'
  root "movies#index"
  # match ':controller(/:action(/:id))', :via => :get



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  delete 'sign_out' => 'user_sessions#destroy'
  get 'users/check_out'
  get 'users/register'
  get 'users/resetArrayChairsId'
  get 'users/pay'
  get 'users/manage_movies' => 'users#manage_movies'

  post 'users/pay'
  post 'users/addSelectedChair'
  post 'users/removeSelectedChair'

  get 'dashboard' => 'users#dashboard'
  get 'login' => 'user_sessions#login'
  get 'ticket/print' => 'tickets#print'
  get 'tickets/rank'

  resources :sessions
  resources :rooms
  resources :theaters
  resources :movies
  resources :user_sessions
  resources :movie_sessions
  resources :tickets, only: [:index]


  resources :users do
  	post :buy_ticket, on: :member
    get :check_out, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :movie_theater
	has_many :sessions
	has_attached_file :image, styles: { medium: "300x300>", thumb: "75x100#" }, default_url: "/assets/missing75x100.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/movie_theater.rb
class MovieTheater < ApplicationRecord
	belongs_to :movie
	belongs_to :theater
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	has_many :tickets
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_one :ticket
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :theater
  belongs_to :template

  def print_theater
    " Theater: #{theater.name} / Room: #{id} / Capacity: #{template.row * template.col}"
  end

  def tickets
    "#{template.row * template.col}"
  end

end

app/models/session.rb
class Session < ApplicationRecord

	belongs_to :room
	belongs_to :movie
	has_many :tickets

	def reservatedchairs
		chairs = []
		puts "--------------------------------------"
		tickets.each do |t|
			puts "--------------------------------------"
			puts t.chair
			puts "--------------------------------------"
			chairs.push(t.chair)
		end
		chairs
	end

end

app/models/template.rb
class Template < ApplicationRecord
	has_many :rooms

	def print_template
		"Columns: #{col} / Rows: #{row} / Total: #{row*col}"
	end
end

app/models/theater.rb
class Theater < ApplicationRecord
	has_many :movie_theater
	has_many :rooms
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :purchase
	belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
	has_many :purchases
	has_many :tickets, :through => :purchases
	has_secure_password

	validates :email, :uniqueness => true

	def is_admin
		self.role.downcase == "admin"
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :needs_clearance, :only => [:index, :edit, :new]

  def index
    @rooms = Room.all.order(:theater_id)
  end

  def new
    @room =Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.capacity = @room.template.col*@room.template.row
    
    if @room.save
      flash[:success] = "Room created"
      redirect_to root_path
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success]="Room edited"
      redirect_to rooms_path
    end
end

  def edit
    @room = Room.find (params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def show
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:theater_id,:template_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_movies_helper.rb
module CrudMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.erb
<!-- Flash -->
<% if flash[:success] or flash[:error] or flash[:info] or flash[:danger] %>
  <div id="message">
    <% if flash[:success] %>
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:success]%>
      </div>
    <%end%>

    <% if flash[:info] %>
      <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:info]%>
      </div>
    <%end%>
    
    <% if flash[:error] %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:error]%><br>
      </div>
    <%end%>

    <% if flash[:danger] %>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[:danger]%><br>
      </div>
    <%end%>

  </div>
<% end %>
<script>
  alertMessage();
</script>
<!-- Flash End -->
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieAndChill</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path, class: "btn btn-success btn-sm" %>
  	<% if current_user.present? %>
      <%= "Logged in as: #{current_user.name} (#{current_user.email}) / " %><%= link_to "log out", sign_out_path, method: :delete %><br>
      <% if current_user.is_admin %>
        <%= link_to "Admin Dashboard", dashboard_path %>
      <% end %>
      <% current_user.purchases.inspect %>
    <% else %>
      <%= link_to "Login", login_path, class: "btn btn-success btn-sm" %>
    <% end %>

  <hr>
  <%= yield %>

  <%= render "layouts/alert" %>

  </body>
</html>